language: php

php:
  - 7.2

install:
  - composer install

before_script:
  - cp .env.example .env
  - php artisan key:generate

script:
  - vendor/bin/phpunit

services:
  - mysql

cache:
  directories:
    - vendor