language: php

php:
  - 7.2

services:
  - mysql

before_script:
  - cp .env.travis .env
  - composer install
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'
  - php artisan migrate

script:
  - php artisan test